### ISSUE TITLE
mysql_secure_installation not working on Debian 9.

### ISSUE THREAD

**Issue by takenek** [ottok/mariadb-10.1#11]
hey
I just install today Debian 9 and got problem with mysql_secure_installation script on MariaDB.
I always after fresh install use this script but this time not working at all:

**Like You see there is no root password:**
root@WWW:~# mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 449
Server version: 10.1.21-MariaDB-5+b1 Debian 9.0

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> quit
Bye

root@WWW:~# mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] Y
New password:
Re-enter new password:
Password updated successfully!
Reloading privilege tables..
 ... Success!

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] Y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] Y
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] Y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] Y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!

**Look still there is no root password!**
root@WWW:~# mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 497
Server version: 10.1.21-MariaDB-5+b1 Debian 9.0

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> quit
Bye

Like You see there is no root password, after i press i want change password it`s not working still password for root is empty :-(

Best Regards
TaKeN

**Comment by ottok** [comment]
This is a duplicate of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855098#15
Please use bugs.debian.org as this is a Debian package in official Debian.

**Comment by takenek** [comment]
Thanks ottok,
so what is official bug tracker for MariaDB? This one or on bugs.debian.org ?

**Comment by ottok** [comment]
The official tracker for the upstream MariaDB project is at jira.mariadb.org. The packaging and distribution of software is done by Linux distributions, and for example unix socket authentication is on by default only in Debian due to how the default settings are made in Debian, thus bugs.debian.org is the right place to discuss fixing this issue (and the issue was linked above).

Thanks for using MariaDB and providing more info to the issue!

**Comment by takenek** [comment]
Thanks
